const q=s=>document.querySelector(s),input=q("#command"),send=q("#send"),conversation=q("#conversation"),toast=q("#toast");
let aiConfigured=false,currentSession=null,pollTimer=null;
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}
function notice(text,error=false){toast.textContent=text;toast.className=`toast show${error?" error":""}`;clearTimeout(notice.t);notice.t=setTimeout(()=>toast.className="toast",3200)}
function add(role,title,text){const el=document.createElement("article");el.className=`message ${role}`;el.innerHTML=`<div class="avatar">${role==="user"?"你":"A"}</div><div><strong>${esc(title)}</strong><p>${esc(text)}</p></div>`;conversation.append(el);el.scrollIntoView({behavior:"smooth",block:"nearest"});return el}
async function api(path,data={},method="POST"){const options={method,headers:{"Content-Type":"application/json"}};if(method!=="GET")options.body=JSON.stringify(data);const response=await fetch(path,options),value=await response.json().catch(()=>({}));if(!response.ok)throw new Error(value.error||"操作失败，请重试。");return value}
async function loadStatus(){try{const status=await api("/api/settings",{},"GET");aiConfigured=Boolean(status.configured);q("#ai-status").classList.toggle("connected",aiConfigured);q("#ai-status").innerHTML=`<i></i>${aiConfigured?`${status.provider_name} · ${status.model}`:"尚未连接模型"}`}catch{}}
function agentHistory(session){return(session.history||[]).map(item=>`${item.status==="success"?"✓":item.status==="failed"?"!":item.status==="blocked"?"○":"·"} ${item.summary}`).join("\n")}
function renderAgent(session){currentSession=session;let card=conversation.querySelector(`[data-agent-session="${session.id}"]`);if(!card){card=add("assistant","通用 Agent 已开始","正在观察电脑…");card.dataset.agentSession=session.id}const title=card.querySelector("strong"),copy=card.querySelector("p"),terminal=["completed","failed","stopped"].includes(session.status);card.classList.toggle("final-answer",terminal);card.querySelector(".actions")?.remove();if(terminal){title.textContent=session.status==="completed"?"最终答复":session.status==="failed"?"未能完成":"任务已停止";copy.textContent=session.message;clearInterval(pollTimer);pollTimer=null;send.disabled=false;currentSession=null;input.placeholder="例如：打开酷狗音乐，搜索周杰伦的歌并播放";return}const body=agentHistory(session);title.textContent=session.status==="needs_input"?"需要你补充信息":"Agent 正在操作";copy.textContent=`${session.message}${body?"\n\n"+body:""}`;if(["running","stopping"].includes(session.status)){const actions=document.createElement("div");actions.className="actions";actions.innerHTML='<button class="secondary" data-agent-stop>紧急停止</button>';card.querySelector("div:nth-child(2)").append(actions)}if(session.status==="needs_input"){clearInterval(pollTimer);pollTimer=null;send.disabled=false;input.placeholder="在这里回答 Agent 的问题"}}
function monitorAgent(session){renderAgent(session);clearInterval(pollTimer);pollTimer=setInterval(async()=>{try{renderAgent(await api(`/api/agent/sessions/${session.id}`,{},"GET"))}catch(error){clearInterval(pollTimer);pollTimer=null;send.disabled=false;notice(error.message,true)}},800)}
async function submit(command=input.value.trim()){if(!command)return input.focus();if(currentSession?.status==="needs_input"){add("user","补充信息",command);input.value="";send.disabled=true;try{monitorAgent(await api("/api/agent/input",{session_id:currentSession.id,answer:command}))}catch(error){notice(error.message,true);send.disabled=false}return}if(currentSession)return notice("请先完成或停止当前任务。",true);if(!aiConfigured){notice("请先在模型中心连接一个 AI 模型。",true);location.href="/models.html";return}add("user","你的目标",command);input.value="";send.disabled=true;try{monitorAgent(await api("/api/agent/start",{goal:command,max_steps:20,autonomous:true,silent:q("#silent-mode").checked}))}catch(error){add("assistant","没有执行成功",error.message);notice(error.message,true);send.disabled=false}}
send.addEventListener("click",()=>submit());input.addEventListener("keydown",event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();submit()}});document.querySelectorAll(".examples button").forEach(button=>button.addEventListener("click",()=>{input.value=button.textContent;submit()}));conversation.addEventListener("click",async event=>{if(!event.target.closest("[data-agent-stop]")||!currentSession)return;try{renderAgent(await api("/api/agent/stop",{session_id:currentSession.id}))}catch(error){notice(error.message,true)}});loadStatus();input.focus();
