const q=selector=>document.querySelector(selector),toast=q("#toast");
let status=null,selectedProvider="deepseek";
function esc(value){return String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char])}
function notice(text,error=false){toast.textContent=text;toast.className=`toast show${error?" error":""}`;clearTimeout(notice.t);notice.t=setTimeout(()=>toast.className="toast",3400)}
async function api(path,data={},method="POST"){const options={method,headers:{"Content-Type":"application/json"}};if(method!=="GET")options.body=JSON.stringify(data);const response=await fetch(path,options),value=await response.json().catch(()=>({}));if(!response.ok)throw new Error(value.error||"操作失败，请重试。");return value}
function definition(){return(status?.providers||[]).find(item=>item.id===selectedProvider)}
function credentialBadge(item){if(!item.requires_key)return item.id==="ollama"?"无需 Key":"Key 可选";return item.manual_model?"Key + 模型 ID":"需要 Key"}
function renderProviders(){const grid=q("#provider-grid");grid.innerHTML=(status.providers||[]).map(item=>`<button class="provider-card${item.id===selectedProvider?" selected":""}" data-provider="${esc(item.id)}"><span>${esc(credentialBadge(item))}</span><strong>${esc(item.name)}</strong><small>${esc(item.description)}</small></button>`).join("");q("#provider-count").textContent=`${status.providers.length} 个明确入口`}
function renderForm(){const item=definition();if(!item)return;q("#provider-title").textContent=item.name;q("#provider-description").textContent=item.description;const editableEndpoint=item.id==="custom"||item.editable_base_url;q("#base-url-field").hidden=!editableEndpoint;q("#base-url").value=editableEndpoint?(status.provider===item.id?status.base_url:item.base_url||""):"";q("#api-key").hidden=!item.requires_key&&item.id==="ollama";q("#api-key-label").hidden=!item.requires_key&&item.id==="ollama";q("#api-key-label").textContent=item.credential_hint;q("#api-key").placeholder=item.requires_key?"粘贴完整 Key；已连接时可留空沿用":"可留空";q("#manual-model-field").hidden=!item.manual_model;q("#manual-model-label").textContent=item.model_hint;q("#manual-model").value=item.manual_model&&status.provider===item.id?status.model:"";q("#connect-provider").textContent=item.id==="ollama"?"连接本机 Ollama 并读取模型":"连接并验证"}
function renderStatus(next){status=next;selectedProvider=selectedProvider||next.provider||"deepseek";const connected=Boolean(next.configured);q("#ai-status").classList.toggle("connected",connected);q("#ai-status").innerHTML=`<i></i>${connected?`${next.provider_name} · ${next.model}`:"尚未连接模型"}`;q("#disconnect-key").hidden=!connected;q("#model-note").textContent=connected?`当前连接：${next.provider_name} / ${next.model}`:"尚未连接";const picker=q("#model-picker"),select=q("#model-select");picker.hidden=!connected||!(next.models||[]).length;if(!picker.hidden){select.innerHTML=next.models.map(model=>`<option value="${esc(model)}"${model===next.model?" selected":""}>${esc(model)}</option>`).join("");q("#current-model").textContent=next.model}renderProviders();renderForm()}
q("#provider-grid").addEventListener("click",event=>{const card=event.target.closest("[data-provider]");if(!card)return;selectedProvider=card.dataset.provider;q("#api-key").value="";q("#manual-model").value="";renderProviders();renderForm()});
q("#connect-provider").addEventListener("click",async event=>{const item=definition();event.target.disabled=true;event.target.textContent="正在连接…";try{const next=await api("/api/settings/provider",{provider:item.id,api_key:q("#api-key").value.trim(),base_url:q("#base-url").value.trim(),model:q("#manual-model").value.trim(),account_id:q("#account-id").value.trim(),account_header:q("#account-header").value.trim()});q("#api-key").value="";selectedProvider=next.provider;renderStatus(next);notice(`已连接 ${next.provider_name}`)}catch(error){notice(error.message,true)}finally{event.target.disabled=false;renderForm()}});
q("#model-select").addEventListener("change",async event=>{try{renderStatus(await api("/api/settings/model",{model:event.target.value}));notice(`已切换到 ${event.target.value}`)}catch(error){notice(error.message,true)}});
q("#disconnect-key").addEventListener("click",async()=>{if(!confirm("断开当前模型，并删除 Windows 凭据库里保存的配置？"))return;selectedProvider="deepseek";renderStatus(await api("/api/settings/deepseek/disconnect",{}));notice("已断开模型服务")});
api("/api/settings",{},"GET").then(next=>{selectedProvider=next.provider||"deepseek";renderStatus(next)}).catch(error=>notice(error.message,true));
